### ISSUE TITLE
Nice Idea Subboards + Question Rye

### ISSUE THREAD

**Issue by Zaloog** [benrutter/boards#2]
Hi, 
I also just released my kanban-cli app `kanban-python` like 2 weeks ago. Also inspired by clikan, although i switched to a more guided workflow with less command typing.

I found your Idea nice to have subboards inside your other boards....
Although I was not able to display it properly with your package.
FYI I quickly tried it out to see how it looks:
![image](https://github.com/benrutter/boards/assets/57259263/4bfeb579-30b0-4b29-885e-763eb288413b)

Idk if its worth implementing though... what is some kind of task/s where you used that kind of feature?
ATM I cant make something up... maybe like a little checklist like table?

I also saw you were using rye.
How did your workflow with it look like? Can you recommend it? Did it make some steps easier?

Best regards

**Comment by benrutter** [comment]
Hey, kanban python looks cool, I'll check it out!

In terms of subboards the main use I have for it is where you're working on multiple projects and want a high level board for all your projects, and then each project to have its own board.

I've never thought about displaying multiple boards at the same time within each other. I love the inception of it all!!

I don't know visually what would work. I think I've seen Trello do a "% complete" on items which is handy. That would probably be a nice touch without overloading the screen to much.

On the rye front I absolutely freaking love it. Previously I would always manually activate virtual environments and go from there, rye basically means I can just not think about virtual environments or anything and just use "python some/file.py" etc and it'll handle all that stuff for me.

**Comment by Zaloog** [comment]
ye that kind of overall board as also something ive been thinking about.

I think Id will make it just as an overview though, and when going back to a project for moving/updating tasks you go to the specific single board view... Since navigation in kanban-python just works with task IDs and each board start from 1 regarding task ID... so I would need a different system there... :P 

hmm I feel pretty config with my alias to change virtualenvs. I have them stored centrally in my home dir and can do something like `act env` to activate it. But I will definitely try Rye in the future. I like the look of the project :)

Can be closed now I guess, thanks for the talk :)
